### ISSUE TITLE
[FEATURE] - Watchlist System

### ISSUE THREAD

**Issue by drkuze** [DiscordLabSCP/DiscordLab#6]
### **Watchlist System:**
1. **Add/Remove Players from Watchlist:**
   - Moderators can add players to the watchlist using a command like `/watchlist add <User-ID/Name> <Reason>`.
   - The reason for adding a player is saved, so other moderators can see why they are being watched.

2. **Remove Players from Watchlist:**
   - A command like `/watchlist remove <User-ID/Name>` allows moderators to remove players from the watchlist when necessary.

3. **View Watchlist:**
   - A command like `/watchlist list` will allow moderators to see all players currently on the watchlist.

4. **Warning System:**
   - Moderators can issue warnings to players on the watchlist with a command like `/watchlist warn <User-ID/Name> <Warning Message>`.
   - No need to specify who issued the warning or the full details of the incident, which helps to keep things simple and reduces workload.

### **Key Benefits:**
- **Better Player Management:** The watchlist allows moderators to keep track of problematic players in a more organized manner.
- **Efficiency:** Moderators can quickly issue warnings and manage the list without the need for extensive manual tracking.
- **Transparency:** Other mods can see why a player is being watched, improving communication and coordination.

**Comment by JayXTQ** [comment]
Due to this format not at all fitting with what the issue template provides. I am closing this. Please reopen.
